### PR TITLE
Please consider some of these changes I've made with the help of ChatGPT

### PR DESCRIPTION
**Pull request by silentoplayz**
Review the code first, as I'd hate for you to make a merge and something does not work well. I used ChatGPT to *improve* the code, but there may be some hiccups. All modifications I've made works well from my testing, just be sure to test it all yourself before including any modifications I've personally made directly into your bot's code.

As for changes I've made, there are many that I was able to document using ChatGPT's help. Here are those changes:

### Configuration and Validation
- **Environment Variable Validation**: Added `validateEnvVariables` function to ensure essential environment variables (`CHANNELS`, `MODEL`, `OLLAMA`, `TOKEN`) are set at startup.
- **Advanced Configuration Options**: Introduced `advancedParams` for custom model parameters (`OPTIONS`), template usage (`USE_TEMPLATE`), and keep-alive settings (`KEEP_ALIVE`).

### Request Handling Improvements
- **Retry Logic**: Enhanced `makeRequest` function with retry logic, including customizable delay (`RETRY_DELAY`), maximum retries (`MAX_RETRIES`), and server unavailable delay (`SERVER_UNAVAILABLE_DELAY`).
- **Server Selection Strategy**: Improved server selection to prioritize available servers, optimizing load distribution.

### User Interaction
- **Dynamic Activity Statuses**: Utilized `ActivityType` to set dynamic activity statuses based on model information, enhancing bot state visibility.
- **New Commands**: Added `.template` and `.license` commands. Updated `.help` command to include these additions, providing more information about the model and its usage.
- **Model Command Enhancement**: Enhanced `.model` command to display detailed model information, including format, family, parameter size, and quantization level.

### Functionality Enhancements
- **Text Splitting**: Refined `splitText` function for sophisticated splitting strategies, ensuring large messages are divided into manageable parts.
- **JSON Parsing and Environment String Handling**: Updated `parseJSONMessage` and `parseEnvString` functions for improved handling and parsing, ensuring robust configuration processing.

### Performance Metrics and Transparency
- **Performance Metrics**: Introduced performance metrics (tokens per second, response time) in bot responses for operational transparency, controlled by the `SHOW_GENERATION_METRICS` environment variable.

### Additional Commands and Features
- **.license Command**: Added to display the model's license information, with handling for long texts by splitting them into multiple messages in a dedicated thread if necessary.
- **Updated Help Command**: The `.help` command now includes the new `.license` command in the list of available commands.

### Retry Configuration
- **Configurable Retry Settings**: The retry delay (`RETRY_DELAY`), maximum number of retries (`MAX_RETRIES`), and server unavailable delay (`SERVER_UNAVAILABLE_DELAY`) are now configurable through environment variables, with defaults applied if not set.

## `.env` file:
- Added a note about using 127.0.0.1 if localhost fails, though the final URL remains http://localhost:11434.
- Introduced a comprehensive JSON object for custom model parameters at runtime.
- Introduced a new TEMPLATE variable for custom formatting of the system, user, and assistant messages.
- Added a new variable for generating response titles (finicky; very prompt & model dependent). 
- USE_TEMPLATE: Introduced and set to false, indicating that the custom template is not used by default but can be enabled.
- GENERATE_TITLE: Introduced and set to false, indicating that automatic title generation for responses is available but not enabled by default.
- SHOW_GENERATION_METRICS: Introduced and set to true, enhancing operational transparency by displaying metrics like response time and tokens per second.
- KEEP_ALIVE: Introduced a new setting to control how long the model stays loaded in memory after a request, set to 30m.
- RETRY_DELAY: Set to 1000, defining the delay between retry attempts.
- MAX_RETRIES: Set to 3, specifying the maximum number of retry attempts for a failed request.
- SERVER_UNAVAILABLE_DELAY: Set to 5000, indicating the delay before retrying when no servers are available.

## `Index.js` file:
- Added an event listener for shard errors to log any errors that occur within a shard.
- Added an event listener for shard disconnects, logging the disconnect event code and reason.
- Added an event listener for shard reconnecting events, indicating when a shard is attempting to reconnect.
- Added an event listener for shard resume events, logging the number of events being replayed upon resumption.
- Modified the shard ready event to include promise handling (.then() and .catch()) for the action of sending data to the shard. 
- Introduced a spawnOptions object to configure shard spawning based on environment variables. This includes the number of shards (SHARD_AMOUNT) and the delay between spawning each shard (SHARD_SPAWN_DELAY).
- Added error handling for the shard spawning process to log any errors that occur.
- Added an event listener for the SIGINT signal (typically triggered by pressing Ctrl+C in the terminal) to perform a graceful shutdown of all shards.

## `README.md` file:
- Complete overhaul!

You can compare the changes made here: https://github.com/mekb-turtle/discord-ai-bot/compare/main...Silentoplayz:discord-ai-bot:main

### CODE REVIEW

**Comment by Silentoplayz** [comment]
I apologize for the 15 commits if you happen to look through all of them. This is also my first ever pull request made. I am hoping you view some of the code as useful and consider some changes. 👍🏼

**Comment by silentoplayz** [comment]
I apologize for the 21 commits if you happen to look through all of them. With that being said, this is my first pull request I've ever made. I am hoping you view some of the code as useful and consider some changes. 👍🏼

Edit: I've found an issue within my own fork where the custom system message that can be set in the .env file called `SYSTEM` works when I type .system to get the system prompt message, but it isn't being utilized by the modelfile as it's system prompt when `USE_SYSTEM=true` is set to `true`. But when I chat around with the model I am using via the Discord bot, it seems to use the custom system prompt I have set in the .env file, so this may just be a visual thing I am unable to change myself in the modelfile shown with `.model` command.

**Comment by sophuric** [comment]
Sorry it took a while to respond. This is a big pull request and a lot of changes. imho, I feel like it would be overkill for a small hobby project, sorry, however do feel free to submit small changes. I may decide to change my mind about this in the future if this project gets big.

**Comment by Silentoplayz** [comment]
Absolutely no problem. I can agree that my entire PR was very messy overall, I'm still new to making these. I apologize for that. As for my forked version of the bot, I'll definitely strive to eventually set aside some time to make the code cleaner and overall better, as I personally do not like what I've done to it in some areas. Feel free to nit pick through the code I've presented in the PR though and test small changes yourself if you'd like to and *yeet* some of those features into your Ollama bot. There's some good stuff in there. 😃

**Pull request closed without merging**
